name: ZAP Scan

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'webgoat'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile

- task: CmdLine@2
  inputs:
    script: 'docker run --name webgoatweb -d -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat:$(Build.BuildId)'
  displayName: 'Execute app in a container'
- task: CmdLine@2
  inputs:
    script: 'ip a'
  displayName: Get host IP

- task: CmdLine@2
  inputs:
    script: |
      DOCKER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' webgoatweb)
      echo This is the docker IP: $DOCKER_IP
      echo "##vso[task.setvariable variable=dockerIp]$DOCKER_IP"
  displayName: Get docker IP
- task: CmdLine@2
  inputs:
    script: 'echo Docker IP from ADO variable: $(dockerIp)'
  displayName: 'echo dockerIp variable'
- task: CmdLine@2
  inputs:
    script: 'curl http://172.17.0.2:8080/WebGoat'
  displayName: 'cURL'
- task: owaspzap@1
  inputs:
    scantype: 'targetedScan'
    url: 'http://$(dockerIp):8080/WebGoat'
    