name: ZAP Scan

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'webgoat'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile

- bash: |
    docker run --name webgoat-site -d -p 8080:8080 -p 9090:9090 webgoat:$(Build.BuildId)
  displayName: 'Running app in a container'

- bash: |
    sleep 60
  displayName: Wait for a minute

- bash: |
    docker logs webgoat-site
- bash: |
    # chmod -R 777  ./
    curl -L http://localhost:8080/WebGoat
    docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://localhost:8080/WebGoat -x xml_report.xml
    true    
  displayName: 'OWASP ZAP Scan'
- powershell: |
    $XslPath = ".ado/utils/xml_to_nunit.xslt" 
    $XmlInputPath = "xml_report.xml"
    $XmlOutputPath = "converted_report.xml"
    $XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
    $XslTransform.Load($XslPath)
    $XslTransform.Transform($XmlInputPath, $XmlOutputPath)
  displayName: 'PowerShell Script'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'converted_report.xml'