on:
  push:
  # schedule:
  #   # Runs every day At 01:00.
  #   - cron:  '0 1 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Build docker image
        run: docker build -t webgoat .
      - name: Execute webgoat in a container
        run: docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -d
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://localhost:8080/WebGoat'